version: "3.5"
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    volumes:
      - cache:/data
    networks:
      - searchNetwork

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - ./server/development.local.env
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - searchNetwork
    depends_on:
      - cache

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - ./web/development.local.env
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - searchNetwork

volumes:
  cache:
    driver: local

networks:
  searchNetwork:
    driver: bridge
